### ISSUE TITLE
Tutorial Pipeline 1: CopyPomFiles.sh

### ISSUE THREAD

**Issue by denise-khuu** [devonfw-tutorials/wiki-tutorials#5]
Write a script which will copy the 'tutorial-pom.xml' template to all tutorial folders. 

Each tutorial folder should have Pom.xml File at the end of the script.

The following links might help you with this task:
https://github.com/devonfw/devonfw.github.io/pull/262
https://github.com/devonfw/architectures/blob/master/solutions/solution-pom.xml
https://github.com/devonfw/architectures/blob/master/solutions/pom.xml

**Comment by denise-khuu** [comment]
Dont forget to add 

#chmod +x wiki-tutorials/scripts/copyPomFiles.sh
#wiki-tutorials/scripts/copyPomFiles.sh

to the devonfw.github.io workflow

**Comment by SchettlerKoehler** [comment]
@denise-khuu please check what is to do here, because the stuff in the pipeline looks already done

**Comment by rvirod** [comment]
asas
